import type { Metadata } from "next";
import {
  Comfortaa,
  Barlow,
  Shippori_Mincho,
  Dela_Gothic_One,
} from "next/font/google";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { Providers } from "./providers";
const jpShippori = Shippori_Mincho({
  weight: ["400", "600", "800"],
  subsets: ["latin"],
  variable: "--font-jpShippori",
});

const jpDela = Dela_Gothic_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-jpDela",
});
const ltComfortaa = Comfortaa({
  variable: "--font-ltComfortaa",
  subsets: ["latin"],
});

const ltBarlow = Barlow({
  weight: ["200", "400", "800"],
  variable: "--font-ltBarlow",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jpDela.variable} ${jpShippori.variable} ${ltBarlow.variable} ${ltComfortaa.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
